using System;
using System.Collections.Generic;
namespace EtwTools
{
    public partial class EtwProvider
    {
        internal static readonly Dictionary<Guid, (string Name, Dictionary<EtwEventDescriptor, string> Events)> s_knownProviders = new()
        {
            { 
                VisualStudioCpsVsProvider.Id,
                (
                    VisualStudioCpsVsProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { VisualStudioCpsVsProvider.EventSourceMessageEvent.Descriptor, VisualStudioCpsVsProvider.EventSourceMessageEvent.Name },
                        { VisualStudioCpsVsProvider.CreateProjectStartEvent.Descriptor, VisualStudioCpsVsProvider.CreateProjectStartEvent.Name },
                        { VisualStudioCpsVsProvider.SetInitialProjectConfigurationStopEvent.Descriptor, VisualStudioCpsVsProvider.SetInitialProjectConfigurationStopEvent.Name },
                        { VisualStudioCpsVsProvider.InitializeProjectNodeStartEvent.Descriptor, VisualStudioCpsVsProvider.InitializeProjectNodeStartEvent.Name },
                        { VisualStudioCpsVsProvider.InitializeProjectNodeStopEvent.Descriptor, VisualStudioCpsVsProvider.InitializeProjectNodeStopEvent.Name },
                        { VisualStudioCpsVsProvider.CreateProjectStopEvent.Descriptor, VisualStudioCpsVsProvider.CreateProjectStopEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingProjectTreeLoadingStopEvent.Descriptor, VisualStudioCpsVsProvider.WaitingProjectTreeLoadingStopEvent.Name },
                        { VisualStudioCpsVsProvider.CpsNotifyTaskStartEvent.Descriptor, VisualStudioCpsVsProvider.CpsNotifyTaskStartEvent.Name },
                        { VisualStudioCpsVsProvider.CreateUnconfiguredProjectStartEvent.Descriptor, VisualStudioCpsVsProvider.CreateUnconfiguredProjectStartEvent.Name },
                        { VisualStudioCpsVsProvider.CreateUnconfiguredProjectStopEvent.Descriptor, VisualStudioCpsVsProvider.CreateUnconfiguredProjectStopEvent.Name },
                        { VisualStudioCpsVsProvider.SetInitialProjectConfigurationStartEvent.Descriptor, VisualStudioCpsVsProvider.SetInitialProjectConfigurationStartEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingProjectTreePublishingStartEvent.Descriptor, VisualStudioCpsVsProvider.WaitingProjectTreePublishingStartEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingProjectTreePublishingStopEvent.Descriptor, VisualStudioCpsVsProvider.WaitingProjectTreePublishingStopEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingLatestReferencesStartEvent.Descriptor, VisualStudioCpsVsProvider.WaitingLatestReferencesStartEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingLatestReferencesStopEvent.Descriptor, VisualStudioCpsVsProvider.WaitingLatestReferencesStopEvent.Name },
                        { VisualStudioCpsVsProvider.CreateProjectAsyncStartEvent.Descriptor, VisualStudioCpsVsProvider.CreateProjectAsyncStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadInitialProjectTreeStartEvent.Descriptor, VisualStudioCpsVsProvider.LoadInitialProjectTreeStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadInitialProjectTreeStopEvent.Descriptor, VisualStudioCpsVsProvider.LoadInitialProjectTreeStopEvent.Name },
                        { VisualStudioCpsVsProvider.CreateDynamicTypeFromRuleStartEvent.Descriptor, VisualStudioCpsVsProvider.CreateDynamicTypeFromRuleStartEvent.Name },
                        { VisualStudioCpsVsProvider.CreateDynamicTypeFromRuleStopEvent.Descriptor, VisualStudioCpsVsProvider.CreateDynamicTypeFromRuleStopEvent.Name },
                        { VisualStudioCpsVsProvider.PublishProjectTreeCoreStartEvent.Descriptor, VisualStudioCpsVsProvider.PublishProjectTreeCoreStartEvent.Name },
                        { VisualStudioCpsVsProvider.PublishProjectTreeCoreStopEvent.Descriptor, VisualStudioCpsVsProvider.PublishProjectTreeCoreStopEvent.Name },
                        { VisualStudioCpsVsProvider.PublishProjectTreeAcquiringLockStartEvent.Descriptor, VisualStudioCpsVsProvider.PublishProjectTreeAcquiringLockStartEvent.Name },
                        { VisualStudioCpsVsProvider.PublishProjectTreeAcquiringLockStopEvent.Descriptor, VisualStudioCpsVsProvider.PublishProjectTreeAcquiringLockStopEvent.Name },
                        { VisualStudioCpsVsProvider.TransferToBestProjectOwnerStartEvent.Descriptor, VisualStudioCpsVsProvider.TransferToBestProjectOwnerStartEvent.Name },
                        { VisualStudioCpsVsProvider.TransferToBestProjectOwnerStopEvent.Descriptor, VisualStudioCpsVsProvider.TransferToBestProjectOwnerStopEvent.Name },
                        { VisualStudioCpsVsProvider.SwitchToMainThreadToPublishTreeFailedEvent.Descriptor, VisualStudioCpsVsProvider.SwitchToMainThreadToPublishTreeFailedEvent.Name },
                        { VisualStudioCpsVsProvider.NotifyBeforeSolutionClosingEvent.Descriptor, VisualStudioCpsVsProvider.NotifyBeforeSolutionClosingEvent.Name },
                        { VisualStudioCpsVsProvider.NotifyQueryStatusDelayEvent.Descriptor, VisualStudioCpsVsProvider.NotifyQueryStatusDelayEvent.Name },
                        { VisualStudioCpsVsProvider.WaitingProjectTreeLoadingStartEvent.Descriptor, VisualStudioCpsVsProvider.WaitingProjectTreeLoadingStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllUnconfiguredProjectsStartEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllUnconfiguredProjectsStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllUnconfiguredProjectsStopEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllUnconfiguredProjectsStopEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllConfiguredProjectsStartEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllConfiguredProjectsStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllConfiguredProjectsStopEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllConfiguredProjectsStopEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllProjectNodesStartEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllProjectNodesStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadAllProjectNodesStopEvent.Descriptor, VisualStudioCpsVsProvider.LoadAllProjectNodesStopEvent.Name },
                        { VisualStudioCpsVsProvider.LoadProjectsAndTreesStartEvent.Descriptor, VisualStudioCpsVsProvider.LoadProjectsAndTreesStartEvent.Name },
                        { VisualStudioCpsVsProvider.LoadProjectsAndTreesStopEvent.Descriptor, VisualStudioCpsVsProvider.LoadProjectsAndTreesStopEvent.Name },
                        { VisualStudioCpsVsProvider.ResetDesignTimeBuilderEvent.Descriptor, VisualStudioCpsVsProvider.ResetDesignTimeBuilderEvent.Name },
                        { VisualStudioCpsVsProvider.CpsHandlersBeforeCloseSolutionStartEvent.Descriptor, VisualStudioCpsVsProvider.CpsHandlersBeforeCloseSolutionStartEvent.Name },
                        { VisualStudioCpsVsProvider.CpsHandlersBeforeCloseSolutionStopEvent.Descriptor, VisualStudioCpsVsProvider.CpsHandlersBeforeCloseSolutionStopEvent.Name },
                        { VisualStudioCpsVsProvider.CpsNotifyTaskStopEvent.Descriptor, VisualStudioCpsVsProvider.CpsNotifyTaskStopEvent.Name },
                        { VisualStudioCpsVsProvider.CpsUpdateSubTypeStartEvent.Descriptor, VisualStudioCpsVsProvider.CpsUpdateSubTypeStartEvent.Name },
                        { VisualStudioCpsVsProvider.CpsUpdateSubTypeEndEvent.Descriptor, VisualStudioCpsVsProvider.CpsUpdateSubTypeEndEvent.Name },
                        { VisualStudioCpsVsProvider.ProjectReloadedInBackgroundEvent.Descriptor, VisualStudioCpsVsProvider.ProjectReloadedInBackgroundEvent.Name },
                    }
                )
            },

            { 
                TplEventSourceProvider.Id,
                (
                    TplEventSourceProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { TplEventSourceProvider.EventSourceMessageEvent.Descriptor, TplEventSourceProvider.EventSourceMessageEvent.Name },
                        { TplEventSourceProvider.ParallelLoopBeginEvent.Descriptor, TplEventSourceProvider.ParallelLoopBeginEvent.Name },
                        { TplEventSourceProvider.ParallelLoopEndEvent.Descriptor, TplEventSourceProvider.ParallelLoopEndEvent.Name },
                        { TplEventSourceProvider.ParallelInvokeBeginEvent.Descriptor, TplEventSourceProvider.ParallelInvokeBeginEvent.Name },
                        { TplEventSourceProvider.ParallelInvokeEndEvent.Descriptor, TplEventSourceProvider.ParallelInvokeEndEvent.Name },
                        { TplEventSourceProvider.ParallelForkEvent.Descriptor, TplEventSourceProvider.ParallelForkEvent.Name },
                        { TplEventSourceProvider.ParallelJoinEvent.Descriptor, TplEventSourceProvider.ParallelJoinEvent.Name },
                        { TplEventSourceProvider.TaskScheduledEvent.Descriptor, TplEventSourceProvider.TaskScheduledEvent.Name },
                        { TplEventSourceProvider.TaskStartedEvent.Descriptor, TplEventSourceProvider.TaskStartedEvent.Name },
                        { TplEventSourceProvider.TaskCompletedEvent.Descriptor, TplEventSourceProvider.TaskCompletedEvent.Name },
                        { TplEventSourceProvider.TaskWaitBeginEvent.Descriptor, TplEventSourceProvider.TaskWaitBeginEvent.Name },
                        { TplEventSourceProvider.TaskWaitEndEvent.Descriptor, TplEventSourceProvider.TaskWaitEndEvent.Name },
                        { TplEventSourceProvider.TaskWaitContinuationCompleteEvent.Descriptor, TplEventSourceProvider.TaskWaitContinuationCompleteEvent.Name },
                        { TplEventSourceProvider.TaskWaitContinuationStartedEvent.Descriptor, TplEventSourceProvider.TaskWaitContinuationStartedEvent.Name },
                        { TplEventSourceProvider.AwaitTaskContinuationScheduledEvent.Descriptor, TplEventSourceProvider.AwaitTaskContinuationScheduledEvent.Name },
                        { TplEventSourceProvider.TraceOperationBeginEvent.Descriptor, TplEventSourceProvider.TraceOperationBeginEvent.Name },
                        { TplEventSourceProvider.TraceOperationRelationEvent.Descriptor, TplEventSourceProvider.TraceOperationRelationEvent.Name },
                        { TplEventSourceProvider.TraceOperationEndEvent.Descriptor, TplEventSourceProvider.TraceOperationEndEvent.Name },
                        { TplEventSourceProvider.TraceSynchronousWorkBeginEvent.Descriptor, TplEventSourceProvider.TraceSynchronousWorkBeginEvent.Name },
                        { TplEventSourceProvider.TraceSynchronousWorkEndEvent.Descriptor, TplEventSourceProvider.TraceSynchronousWorkEndEvent.Name },
                        { TplEventSourceProvider.RunningContinuationEvent.Descriptor, TplEventSourceProvider.RunningContinuationEvent.Name },
                        { TplEventSourceProvider.RunningContinuationListEvent.Descriptor, TplEventSourceProvider.RunningContinuationListEvent.Name },
                        { TplEventSourceProvider.DebugMessageEvent.Descriptor, TplEventSourceProvider.DebugMessageEvent.Name },
                        { TplEventSourceProvider.DebugFacilityMessageEvent.Descriptor, TplEventSourceProvider.DebugFacilityMessageEvent.Name },
                        { TplEventSourceProvider.DebugFacilityMessage1Event.Descriptor, TplEventSourceProvider.DebugFacilityMessage1Event.Name },
                        { TplEventSourceProvider.SetActivityIdEvent.Descriptor, TplEventSourceProvider.SetActivityIdEvent.Name },
                        { TplEventSourceProvider.NewIDEvent.Descriptor, TplEventSourceProvider.NewIDEvent.Name },
                    }
                )
            },

            { 
                KernelThreadProvider.Id,
                (
                    KernelThreadProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { KernelThreadProvider.SetNameEvent.Descriptor, KernelThreadProvider.SetNameEvent.Name },
                        { KernelThreadProvider.CompCSEvent.Descriptor, KernelThreadProvider.CompCSEvent.Name },
                        { KernelThreadProvider.SpinLockEvent.Descriptor, KernelThreadProvider.SpinLockEvent.Name },
                        { KernelThreadProvider.ReadyThreadEvent.Descriptor, KernelThreadProvider.ReadyThreadEvent.Name },
                        { KernelThreadProvider.ThreadAffinityEvent.Descriptor, KernelThreadProvider.ThreadAffinityEvent.Name },
                        { KernelThreadProvider.WorkerThreadEvent.Descriptor, KernelThreadProvider.WorkerThreadEvent.Name },
                        { KernelThreadProvider.AntiStarvationBoostEvent.Descriptor, KernelThreadProvider.AntiStarvationBoostEvent.Name },
                        { KernelThreadProvider.ThreadMigrationEvent.Descriptor, KernelThreadProvider.ThreadMigrationEvent.Name },
                        { KernelThreadProvider.KernelQueueEnqueueEvent.Descriptor, KernelThreadProvider.KernelQueueEnqueueEvent.Name },
                        { KernelThreadProvider.KernelQueueDequeueEvent.Descriptor, KernelThreadProvider.KernelQueueDequeueEvent.Name },
                        { KernelThreadProvider.WorkerThreadStartEvent.Descriptor, KernelThreadProvider.WorkerThreadStartEvent.Name },
                        { KernelThreadProvider.WorkerThreadEndEvent.Descriptor, KernelThreadProvider.WorkerThreadEndEvent.Name },
                        { KernelThreadProvider.AutoBoostSetFloorEvent.Descriptor, KernelThreadProvider.AutoBoostSetFloorEvent.Name },
                        { KernelThreadProvider.AutoBoostClearFloorEvent.Descriptor, KernelThreadProvider.AutoBoostClearFloorEvent.Name },
                        { KernelThreadProvider.AutoBoostEntryExhaustionEvent.Descriptor, KernelThreadProvider.AutoBoostEntryExhaustionEvent.Name },
                        { KernelThreadProvider.SubProcessTagChangedEvent.Descriptor, KernelThreadProvider.SubProcessTagChangedEvent.Name },
                        { KernelThreadProvider.SetPriorityEvent.Descriptor, KernelThreadProvider.SetPriorityEvent.Name },
                        { KernelThreadProvider.SetBasePriorityEvent.Descriptor, KernelThreadProvider.SetBasePriorityEvent.Name },
                        { KernelThreadProvider.SetPagePriorityEvent.Descriptor, KernelThreadProvider.SetPagePriorityEvent.Name },
                        { KernelThreadProvider.SetIoPriorityEvent.Descriptor, KernelThreadProvider.SetIoPriorityEvent.Name },
                        { KernelThreadProvider.ThreadStartEvent.Descriptor, KernelThreadProvider.ThreadStartEvent.Name },
                        { KernelThreadProvider.ThreadEndEvent.Descriptor, KernelThreadProvider.ThreadEndEvent.Name },
                        { KernelThreadProvider.DataCollectionStartEvent.Descriptor, KernelThreadProvider.DataCollectionStartEvent.Name },
                        { KernelThreadProvider.DataCollectionEndEvent.Descriptor, KernelThreadProvider.DataCollectionEndEvent.Name },
                        { KernelThreadProvider.CSwitchEvent.Descriptor, KernelThreadProvider.CSwitchEvent.Name },
                    }
                )
            },

            { 
                VisualStudioThreadingProvider.Id,
                (
                    VisualStudioThreadingProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { VisualStudioThreadingProvider.EventSourceMessageEvent.Descriptor, VisualStudioThreadingProvider.EventSourceMessageEvent.Name },
                        { VisualStudioThreadingProvider.CompleteOnCurrentThreadStopEvent.Descriptor, VisualStudioThreadingProvider.CompleteOnCurrentThreadStopEvent.Name },
                        { VisualStudioThreadingProvider.WaitSynchronouslyStartEvent.Descriptor, VisualStudioThreadingProvider.WaitSynchronouslyStartEvent.Name },
                        { VisualStudioThreadingProvider.WaitSynchronouslyStopEvent.Descriptor, VisualStudioThreadingProvider.WaitSynchronouslyStopEvent.Name },
                        { VisualStudioThreadingProvider.PostExecutionStopEvent.Descriptor, VisualStudioThreadingProvider.PostExecutionStopEvent.Name },
                        { VisualStudioThreadingProvider.CircularJoinableTaskDependencyDetectedEvent.Descriptor, VisualStudioThreadingProvider.CircularJoinableTaskDependencyDetectedEvent.Name },
                        { VisualStudioThreadingProvider.ReaderWriterLockIssuedEvent.Descriptor, VisualStudioThreadingProvider.ReaderWriterLockIssuedEvent.Name },
                        { VisualStudioThreadingProvider.WaitReaderWriterLockStartEvent.Descriptor, VisualStudioThreadingProvider.WaitReaderWriterLockStartEvent.Name },
                        { VisualStudioThreadingProvider.WaitReaderWriterLockStopEvent.Descriptor, VisualStudioThreadingProvider.WaitReaderWriterLockStopEvent.Name },
                        { VisualStudioThreadingProvider.CompleteOnCurrentThreadStartEvent.Descriptor, VisualStudioThreadingProvider.CompleteOnCurrentThreadStartEvent.Name },
                        { VisualStudioThreadingProvider.PostExecutionStartEvent.Descriptor, VisualStudioThreadingProvider.PostExecutionStartEvent.Name },
                    }
                )
            },

            { 
                ApplicationInsightsCoreProvider.Id,
                (
                    ApplicationInsightsCoreProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { ApplicationInsightsCoreProvider.EventSourceMessageEvent.Descriptor, ApplicationInsightsCoreProvider.EventSourceMessageEvent.Name },
                        { ApplicationInsightsCoreProvider.LogVerboseEvent.Descriptor, ApplicationInsightsCoreProvider.LogVerboseEvent.Name },
                        { ApplicationInsightsCoreProvider.DiagnosticsEventThrottlingHasBeenStartedForTheEventEvent.Descriptor, ApplicationInsightsCoreProvider.DiagnosticsEventThrottlingHasBeenStartedForTheEventEvent.Name },
                        { ApplicationInsightsCoreProvider.DiagnosticsEventThrottlingHasBeenResetForTheEventEvent.Descriptor, ApplicationInsightsCoreProvider.DiagnosticsEventThrottlingHasBeenResetForTheEventEvent.Name },
                        { ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerDisposeTimerFailureEvent.Descriptor, ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerDisposeTimerFailureEvent.Name },
                        { ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerTimerWasCreatedEvent.Descriptor, ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerTimerWasCreatedEvent.Name },
                        { ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerTimerWasRemovedEvent.Descriptor, ApplicationInsightsCoreProvider.DiagnoisticsEventThrottlingSchedulerTimerWasRemovedEvent.Name },
                        { ApplicationInsightsCoreProvider.TelemetryClientConstructorWithNoTelemetryConfigurationEvent.Descriptor, ApplicationInsightsCoreProvider.TelemetryClientConstructorWithNoTelemetryConfigurationEvent.Name },
                        { ApplicationInsightsCoreProvider.PopulateRequiredStringWithValueEvent.Descriptor, ApplicationInsightsCoreProvider.PopulateRequiredStringWithValueEvent.Name },
                        { ApplicationInsightsCoreProvider.RequestTelemetryIncorrectDurationEvent.Descriptor, ApplicationInsightsCoreProvider.RequestTelemetryIncorrectDurationEvent.Name },
                        { ApplicationInsightsCoreProvider.TrackingWasDisabledEvent.Descriptor, ApplicationInsightsCoreProvider.TrackingWasDisabledEvent.Name },
                        { ApplicationInsightsCoreProvider.TrackingWasEnabledEvent.Descriptor, ApplicationInsightsCoreProvider.TrackingWasEnabledEvent.Name },
                        { ApplicationInsightsCoreProvider.LogErrorEvent.Descriptor, ApplicationInsightsCoreProvider.LogErrorEvent.Name },
                        { ApplicationInsightsCoreProvider.BuildInfoConfigBrokenXmlErrorEvent.Descriptor, ApplicationInsightsCoreProvider.BuildInfoConfigBrokenXmlErrorEvent.Name },
                    }
                )
            },

            { 
                FrameworkEventSourceProvider.Id,
                (
                    FrameworkEventSourceProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { FrameworkEventSourceProvider.EventSourceMessageEvent.Descriptor, FrameworkEventSourceProvider.EventSourceMessageEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerLookupStartedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerLookupStartedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerLookingForResourceSetEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerLookingForResourceSetEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerFoundResourceSetInCacheEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerFoundResourceSetInCacheEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerFoundResourceSetInCacheUnexpectedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerFoundResourceSetInCacheUnexpectedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerStreamFoundEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerStreamFoundEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerStreamNotFoundEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerStreamNotFoundEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerGetSatelliteAssemblySucceededEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerGetSatelliteAssemblySucceededEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerGetSatelliteAssemblyFailedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerGetSatelliteAssemblyFailedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerCaseInsensitiveResourceStreamLookupSucceededEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerCaseInsensitiveResourceStreamLookupSucceededEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerCaseInsensitiveResourceStreamLookupFailedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerCaseInsensitiveResourceStreamLookupFailedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerManifestResourceAccessDeniedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerManifestResourceAccessDeniedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerNeutralResourcesSufficientEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerNeutralResourcesSufficientEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerNeutralResourceAttributeMissingEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerNeutralResourceAttributeMissingEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerCreatingResourceSetEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerCreatingResourceSetEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerNotCreatingResourceSetEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerNotCreatingResourceSetEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerLookupFailedEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerLookupFailedEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerReleasingResourcesEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerReleasingResourcesEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerNeutralResourcesNotFoundEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerNeutralResourcesNotFoundEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerNeutralResourcesFoundEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerNeutralResourcesFoundEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerAddingCultureFromConfigFileEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerAddingCultureFromConfigFileEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerCultureNotFoundInConfigFileEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerCultureNotFoundInConfigFileEvent.Name },
                        { FrameworkEventSourceProvider.ResourceManagerCultureFoundInConfigFileEvent.Descriptor, FrameworkEventSourceProvider.ResourceManagerCultureFoundInConfigFileEvent.Name },
                        { FrameworkEventSourceProvider.ThreadPoolEnqueueWorkEvent.Descriptor, FrameworkEventSourceProvider.ThreadPoolEnqueueWorkEvent.Name },
                        { FrameworkEventSourceProvider.ThreadPoolDequeueWorkEvent.Descriptor, FrameworkEventSourceProvider.ThreadPoolDequeueWorkEvent.Name },
                        { FrameworkEventSourceProvider.GetResponseStartEvent.Descriptor, FrameworkEventSourceProvider.GetResponseStartEvent.Name },
                        { FrameworkEventSourceProvider.GetResponseStopEvent.Descriptor, FrameworkEventSourceProvider.GetResponseStopEvent.Name },
                        { FrameworkEventSourceProvider.GetRequestStreamStartEvent.Descriptor, FrameworkEventSourceProvider.GetRequestStreamStartEvent.Name },
                        { FrameworkEventSourceProvider.GetRequestStreamStopEvent.Descriptor, FrameworkEventSourceProvider.GetRequestStreamStopEvent.Name },
                        { FrameworkEventSourceProvider.ThreadTransferSendEvent.Descriptor, FrameworkEventSourceProvider.ThreadTransferSendEvent.Name },
                        { FrameworkEventSourceProvider.ThreadTransferReceiveEvent.Descriptor, FrameworkEventSourceProvider.ThreadTransferReceiveEvent.Name },
                        { FrameworkEventSourceProvider.ThreadTransferReceiveHandledEvent.Descriptor, FrameworkEventSourceProvider.ThreadTransferReceiveHandledEvent.Name },
                    }
                )
            },

            { 
                RoslynEventSourceProvider.Id,
                (
                    RoslynEventSourceProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { RoslynEventSourceProvider.EventSourceMessageEvent.Descriptor, RoslynEventSourceProvider.EventSourceMessageEvent.Name },
                        { RoslynEventSourceProvider.LogEvent.Descriptor, RoslynEventSourceProvider.LogEvent.Name },
                        { RoslynEventSourceProvider.BlockStartEvent.Descriptor, RoslynEventSourceProvider.BlockStartEvent.Name },
                        { RoslynEventSourceProvider.BlockStopEvent.Descriptor, RoslynEventSourceProvider.BlockStopEvent.Name },
                        { RoslynEventSourceProvider.SendFunctionDefinitionsEvent.Descriptor, RoslynEventSourceProvider.SendFunctionDefinitionsEvent.Name },
                        { RoslynEventSourceProvider.BlockCanceledEvent.Descriptor, RoslynEventSourceProvider.BlockCanceledEvent.Name },
                        { RoslynEventSourceProvider.OnEventCommandEvent.Descriptor, RoslynEventSourceProvider.OnEventCommandEvent.Name },
                    }
                )
            },

            { 
                KernelPerfInfoProvider.Id,
                (
                    KernelPerfInfoProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { KernelPerfInfoProvider.MarkEvent.Descriptor, KernelPerfInfoProvider.MarkEvent.Name },
                        { KernelPerfInfoProvider.SampleProfEvent.Descriptor, KernelPerfInfoProvider.SampleProfEvent.Name },
                        { KernelPerfInfoProvider.PmcCounterProfEvent.Descriptor, KernelPerfInfoProvider.PmcCounterProfEvent.Name },
                        { KernelPerfInfoProvider.SetIntervalEvent.Descriptor, KernelPerfInfoProvider.SetIntervalEvent.Name },
                        { KernelPerfInfoProvider.PmcCtrConfigEvent.Descriptor, KernelPerfInfoProvider.PmcCtrConfigEvent.Name },
                        { KernelPerfInfoProvider.SysClEnterEvent.Descriptor, KernelPerfInfoProvider.SysClEnterEvent.Name },
                        { KernelPerfInfoProvider.SysClExitEvent.Descriptor, KernelPerfInfoProvider.SysClExitEvent.Name },
                        { KernelPerfInfoProvider.ISREvent.Descriptor, KernelPerfInfoProvider.ISREvent.Name },
                        { KernelPerfInfoProvider.ISR_PASSEvent.Descriptor, KernelPerfInfoProvider.ISR_PASSEvent.Name },
                        { KernelPerfInfoProvider.ISR_MSIEvent.Descriptor, KernelPerfInfoProvider.ISR_MSIEvent.Name },
                        { KernelPerfInfoProvider.ISR_UnexpectedEvent.Descriptor, KernelPerfInfoProvider.ISR_UnexpectedEvent.Name },
                        { KernelPerfInfoProvider.ThreadedDPCEvent.Descriptor, KernelPerfInfoProvider.ThreadedDPCEvent.Name },
                        { KernelPerfInfoProvider.DPCEvent.Descriptor, KernelPerfInfoProvider.DPCEvent.Name },
                        { KernelPerfInfoProvider.TimerDPCEvent.Descriptor, KernelPerfInfoProvider.TimerDPCEvent.Name },
                        { KernelPerfInfoProvider.IOTimerEvent.Descriptor, KernelPerfInfoProvider.IOTimerEvent.Name },
                        { KernelPerfInfoProvider.WdfDPCEvent.Descriptor, KernelPerfInfoProvider.WdfDPCEvent.Name },
                        { KernelPerfInfoProvider.WdfISREvent.Descriptor, KernelPerfInfoProvider.WdfISREvent.Name },
                        { KernelPerfInfoProvider.WdfPassiveISREvent.Descriptor, KernelPerfInfoProvider.WdfPassiveISREvent.Name },
                        { KernelPerfInfoProvider.WdfWorkItemEvent.Descriptor, KernelPerfInfoProvider.WdfWorkItemEvent.Name },
                        { KernelPerfInfoProvider.DebuggerEnabledEvent.Descriptor, KernelPerfInfoProvider.DebuggerEnabledEvent.Name },
                        { KernelPerfInfoProvider.IoStartTimerEvent.Descriptor, KernelPerfInfoProvider.IoStartTimerEvent.Name },
                        { KernelPerfInfoProvider.IoStopTimerEvent.Descriptor, KernelPerfInfoProvider.IoStopTimerEvent.Name },
                        { KernelPerfInfoProvider.SetKTimer2Event.Descriptor, KernelPerfInfoProvider.SetKTimer2Event.Name },
                        { KernelPerfInfoProvider.ExpireKTimer2Event.Descriptor, KernelPerfInfoProvider.ExpireKTimer2Event.Name },
                        { KernelPerfInfoProvider.CancelKTimer2Event.Descriptor, KernelPerfInfoProvider.CancelKTimer2Event.Name },
                        { KernelPerfInfoProvider.DisableKTimer2Event.Descriptor, KernelPerfInfoProvider.DisableKTimer2Event.Name },
                        { KernelPerfInfoProvider.FinalizeKTimer2Event.Descriptor, KernelPerfInfoProvider.FinalizeKTimer2Event.Name },
                        { KernelPerfInfoProvider.KernelHypercallEvent.Descriptor, KernelPerfInfoProvider.KernelHypercallEvent.Name },
                        { KernelPerfInfoProvider.SampledProfileIntervalCollectionStartEvent.Descriptor, KernelPerfInfoProvider.SampledProfileIntervalCollectionStartEvent.Name },
                        { KernelPerfInfoProvider.SampledProfileIntervalCollectionEndEvent.Descriptor, KernelPerfInfoProvider.SampledProfileIntervalCollectionEndEvent.Name },
                        { KernelPerfInfoProvider.SpinlockConfigureCollectionStartEvent.Descriptor, KernelPerfInfoProvider.SpinlockConfigureCollectionStartEvent.Name },
                        { KernelPerfInfoProvider.SpinlockConfigureCollectionEndEvent.Descriptor, KernelPerfInfoProvider.SpinlockConfigureCollectionEndEvent.Name },
                    }
                )
            },

            { 
                KernelStackWalkProvider.Id,
                (
                    KernelStackWalkProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { KernelStackWalkProvider.StackEvent.Descriptor, KernelStackWalkProvider.StackEvent.Name },
                        { KernelStackWalkProvider.StackKeyCreateEvent.Descriptor, KernelStackWalkProvider.StackKeyCreateEvent.Name },
                        { KernelStackWalkProvider.StackKeyDeleteEvent.Descriptor, KernelStackWalkProvider.StackKeyDeleteEvent.Name },
                        { KernelStackWalkProvider.StackKeyRundownEvent.Descriptor, KernelStackWalkProvider.StackKeyRundownEvent.Name },
                        { KernelStackWalkProvider.StackKeyKernelEvent.Descriptor, KernelStackWalkProvider.StackKeyKernelEvent.Name },
                        { KernelStackWalkProvider.StackKeyUserEvent.Descriptor, KernelStackWalkProvider.StackKeyUserEvent.Name },
                    }
                )
            },

            { 
                DotnetRuntimeProvider.Id,
                (
                    DotnetRuntimeProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { DotnetRuntimeProvider.TypeBulkTypeEvent.Descriptor, DotnetRuntimeProvider.TypeBulkTypeEvent.Name },
                        { DotnetRuntimeProvider.GCBulkRootEdgeEvent.Descriptor, DotnetRuntimeProvider.GCBulkRootEdgeEvent.Name },
                        { DotnetRuntimeProvider.GCBulkRootConditionalWeakTableElementEdgeEvent.Descriptor, DotnetRuntimeProvider.GCBulkRootConditionalWeakTableElementEdgeEvent.Name },
                        { DotnetRuntimeProvider.GCBulkNodeEvent.Descriptor, DotnetRuntimeProvider.GCBulkNodeEvent.Name },
                        { DotnetRuntimeProvider.GCBulkEdgeEvent.Descriptor, DotnetRuntimeProvider.GCBulkEdgeEvent.Name },
                        { DotnetRuntimeProvider.GCSampledObjectAllocationHighEvent.Descriptor, DotnetRuntimeProvider.GCSampledObjectAllocationHighEvent.Name },
                        { DotnetRuntimeProvider.GCBulkSurvivingObjectRangesEvent.Descriptor, DotnetRuntimeProvider.GCBulkSurvivingObjectRangesEvent.Name },
                        { DotnetRuntimeProvider.GCBulkMovedObjectRangesEvent.Descriptor, DotnetRuntimeProvider.GCBulkMovedObjectRangesEvent.Name },
                        { DotnetRuntimeProvider.GCGenerationRangeEvent.Descriptor, DotnetRuntimeProvider.GCGenerationRangeEvent.Name },
                        { DotnetRuntimeProvider.GCMarkStackRootsEvent.Descriptor, DotnetRuntimeProvider.GCMarkStackRootsEvent.Name },
                        { DotnetRuntimeProvider.GCMarkFinalizeQueueRootsEvent.Descriptor, DotnetRuntimeProvider.GCMarkFinalizeQueueRootsEvent.Name },
                        { DotnetRuntimeProvider.GCMarkHandlesEvent.Descriptor, DotnetRuntimeProvider.GCMarkHandlesEvent.Name },
                        { DotnetRuntimeProvider.GCMarkCardsEvent.Descriptor, DotnetRuntimeProvider.GCMarkCardsEvent.Name },
                        { DotnetRuntimeProvider.GCFinalizeObjectEvent.Descriptor, DotnetRuntimeProvider.GCFinalizeObjectEvent.Name },
                        { DotnetRuntimeProvider.GCSetGCHandleEvent.Descriptor, DotnetRuntimeProvider.GCSetGCHandleEvent.Name },
                        { DotnetRuntimeProvider.GCDestoryGCHandleEvent.Descriptor, DotnetRuntimeProvider.GCDestoryGCHandleEvent.Name },
                        { DotnetRuntimeProvider.GCSampledObjectAllocationLowEvent.Descriptor, DotnetRuntimeProvider.GCSampledObjectAllocationLowEvent.Name },
                        { DotnetRuntimeProvider.GCPinObjectAtGCTimeEvent.Descriptor, DotnetRuntimeProvider.GCPinObjectAtGCTimeEvent.Name },
                        { DotnetRuntimeProvider.GCTriggeredEvent.Descriptor, DotnetRuntimeProvider.GCTriggeredEvent.Name },
                        { DotnetRuntimeProvider.GCBulkRootCCWEvent.Descriptor, DotnetRuntimeProvider.GCBulkRootCCWEvent.Name },
                        { DotnetRuntimeProvider.GCBulkRCWEvent.Descriptor, DotnetRuntimeProvider.GCBulkRCWEvent.Name },
                        { DotnetRuntimeProvider.GCBulkRootStaticVarEvent.Descriptor, DotnetRuntimeProvider.GCBulkRootStaticVarEvent.Name },
                        { DotnetRuntimeProvider.GCDynamicEventEvent.Descriptor, DotnetRuntimeProvider.GCDynamicEventEvent.Name },
                        { DotnetRuntimeProvider.WorkerThreadCreationV2StartEvent.Descriptor, DotnetRuntimeProvider.WorkerThreadCreationV2StartEvent.Name },
                        { DotnetRuntimeProvider.WorkerThreadCreationV2StopEvent.Descriptor, DotnetRuntimeProvider.WorkerThreadCreationV2StopEvent.Name },
                        { DotnetRuntimeProvider.WorkerThreadRetirementV2StartEvent.Descriptor, DotnetRuntimeProvider.WorkerThreadRetirementV2StartEvent.Name },
                        { DotnetRuntimeProvider.WorkerThreadRetirementV2StopEvent.Descriptor, DotnetRuntimeProvider.WorkerThreadRetirementV2StopEvent.Name },
                        { DotnetRuntimeProvider.ThreadpoolSuspensionV2StartEvent.Descriptor, DotnetRuntimeProvider.ThreadpoolSuspensionV2StartEvent.Name },
                        { DotnetRuntimeProvider.ThreadpoolSuspensionV2StopEvent.Descriptor, DotnetRuntimeProvider.ThreadpoolSuspensionV2StopEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadStartEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadStartEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadStopEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadStopEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadRetirementStartEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadRetirementStartEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadRetirementStopEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadRetirementStopEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentSampleEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentSampleEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentAdjustmentEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentAdjustmentEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentStatsEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadAdjustmentStatsEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkerThreadWaitEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkerThreadWaitEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolWorkingThreadCountStartEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolWorkingThreadCountStartEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolEnqueueEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolEnqueueEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolDequeueEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolDequeueEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolIOEnqueueEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolIOEnqueueEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolIODequeueEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolIODequeueEvent.Name },
                        { DotnetRuntimeProvider.ThreadPoolIOPackEvent.Descriptor, DotnetRuntimeProvider.ThreadPoolIOPackEvent.Name },
                        { DotnetRuntimeProvider.ThreadCreatingEvent.Descriptor, DotnetRuntimeProvider.ThreadCreatingEvent.Name },
                        { DotnetRuntimeProvider.ThreadRunningEvent.Descriptor, DotnetRuntimeProvider.ThreadRunningEvent.Name },
                        { DotnetRuntimeProvider.ClrStackWalkEvent.Descriptor, DotnetRuntimeProvider.ClrStackWalkEvent.Name },
                        { DotnetRuntimeProvider.AppDomainResourceManagementMemAllocatedEvent.Descriptor, DotnetRuntimeProvider.AppDomainResourceManagementMemAllocatedEvent.Name },
                        { DotnetRuntimeProvider.AppDomainResourceManagementMemSurvivedEvent.Descriptor, DotnetRuntimeProvider.AppDomainResourceManagementMemSurvivedEvent.Name },
                        { DotnetRuntimeProvider.AppDomainResourceManagementThreadCreatedEvent.Descriptor, DotnetRuntimeProvider.AppDomainResourceManagementThreadCreatedEvent.Name },
                        { DotnetRuntimeProvider.AppDomainResourceManagementThreadTerminatedEvent.Descriptor, DotnetRuntimeProvider.AppDomainResourceManagementThreadTerminatedEvent.Name },
                        { DotnetRuntimeProvider.AppDomainResourceManagementDomainEnterEvent.Descriptor, DotnetRuntimeProvider.AppDomainResourceManagementDomainEnterEvent.Name },
                        { DotnetRuntimeProvider.ILStubStubGeneratedEvent.Descriptor, DotnetRuntimeProvider.ILStubStubGeneratedEvent.Name },
                        { DotnetRuntimeProvider.ILStubStubCacheHitEvent.Descriptor, DotnetRuntimeProvider.ILStubStubCacheHitEvent.Name },
                        { DotnetRuntimeProvider.ContentionStopEvent.Descriptor, DotnetRuntimeProvider.ContentionStopEvent.Name },
                        { DotnetRuntimeProvider.MethodDCStartCompleteV2Event.Descriptor, DotnetRuntimeProvider.MethodDCStartCompleteV2Event.Name },
                        { DotnetRuntimeProvider.MethodDCEndCompleteV2Event.Descriptor, DotnetRuntimeProvider.MethodDCEndCompleteV2Event.Name },
                        { DotnetRuntimeProvider.MethodDCStartV2Event.Descriptor, DotnetRuntimeProvider.MethodDCStartV2Event.Name },
                        { DotnetRuntimeProvider.MethodDCStopV2Event.Descriptor, DotnetRuntimeProvider.MethodDCStopV2Event.Name },
                        { DotnetRuntimeProvider.MethodDCStartVerboseV2Event.Descriptor, DotnetRuntimeProvider.MethodDCStartVerboseV2Event.Name },
                        { DotnetRuntimeProvider.MethodDCStopVerboseV2Event.Descriptor, DotnetRuntimeProvider.MethodDCStopVerboseV2Event.Name },
                        { DotnetRuntimeProvider.LoaderModuleDCStartV2Event.Descriptor, DotnetRuntimeProvider.LoaderModuleDCStartV2Event.Name },
                        { DotnetRuntimeProvider.LoaderModuleDCStopV2Event.Descriptor, DotnetRuntimeProvider.LoaderModuleDCStopV2Event.Name },
                        { DotnetRuntimeProvider.ClrPerfTrackModuleRangeLoadEvent.Descriptor, DotnetRuntimeProvider.ClrPerfTrackModuleRangeLoadEvent.Name },
                        { DotnetRuntimeProvider.MethodInliningSucceededEvent.Descriptor, DotnetRuntimeProvider.MethodInliningSucceededEvent.Name },
                        { DotnetRuntimeProvider.MethodInliningFailedEvent.Descriptor, DotnetRuntimeProvider.MethodInliningFailedEvent.Name },
                        { DotnetRuntimeProvider.RuntimeStartEvent.Descriptor, DotnetRuntimeProvider.RuntimeStartEvent.Name },
                        { DotnetRuntimeProvider.MethodTailCallSucceededEvent.Descriptor, DotnetRuntimeProvider.MethodTailCallSucceededEvent.Name },
                        { DotnetRuntimeProvider.MethodTailCallFailedEvent.Descriptor, DotnetRuntimeProvider.MethodTailCallFailedEvent.Name },
                        { DotnetRuntimeProvider.MethodMethodILToNativeMapEvent.Descriptor, DotnetRuntimeProvider.MethodMethodILToNativeMapEvent.Name },
                        { DotnetRuntimeProvider.GCIncreaseMemoryPressureEvent.Descriptor, DotnetRuntimeProvider.GCIncreaseMemoryPressureEvent.Name },
                        { DotnetRuntimeProvider.GCDecreaseMemoryPressureEvent.Descriptor, DotnetRuntimeProvider.GCDecreaseMemoryPressureEvent.Name },
                        { DotnetRuntimeProvider.GCMarkEvent.Descriptor, DotnetRuntimeProvider.GCMarkEvent.Name },
                        { DotnetRuntimeProvider.GCLoadedEvent.Descriptor, DotnetRuntimeProvider.GCLoadedEvent.Name },
                        { DotnetRuntimeProvider.DebugIPCEventStartEvent.Descriptor, DotnetRuntimeProvider.DebugIPCEventStartEvent.Name },
                        { DotnetRuntimeProvider.DebugIPCEventStopEvent.Descriptor, DotnetRuntimeProvider.DebugIPCEventStopEvent.Name },
                        { DotnetRuntimeProvider.DebugExceptionProcessingStartEvent.Descriptor, DotnetRuntimeProvider.DebugExceptionProcessingStartEvent.Name },
                        { DotnetRuntimeProvider.DebugExceptionProcessingStopEvent.Descriptor, DotnetRuntimeProvider.DebugExceptionProcessingStopEvent.Name },
                        { DotnetRuntimeProvider.ExceptionCatchStartEvent.Descriptor, DotnetRuntimeProvider.ExceptionCatchStartEvent.Name },
                        { DotnetRuntimeProvider.ExceptionCatchStopEvent.Descriptor, DotnetRuntimeProvider.ExceptionCatchStopEvent.Name },
                        { DotnetRuntimeProvider.ExceptionFinallyStartEvent.Descriptor, DotnetRuntimeProvider.ExceptionFinallyStartEvent.Name },
                        { DotnetRuntimeProvider.ExceptionFinallyStopEvent.Descriptor, DotnetRuntimeProvider.ExceptionFinallyStopEvent.Name },
                        { DotnetRuntimeProvider.ExceptionFilterStartEvent.Descriptor, DotnetRuntimeProvider.ExceptionFilterStartEvent.Name },
                        { DotnetRuntimeProvider.ExceptionFilterStopEvent.Descriptor, DotnetRuntimeProvider.ExceptionFilterStopEvent.Name },
                        { DotnetRuntimeProvider.ExceptionStopEvent.Descriptor, DotnetRuntimeProvider.ExceptionStopEvent.Name },
                        { DotnetRuntimeProvider.GCStopEvent.Descriptor, DotnetRuntimeProvider.GCStopEvent.Name },
                        { DotnetRuntimeProvider.GCRestartEEStopEvent.Descriptor, DotnetRuntimeProvider.GCRestartEEStopEvent.Name },
                        { DotnetRuntimeProvider.GCHeapStatsEvent.Descriptor, DotnetRuntimeProvider.GCHeapStatsEvent.Name },
                        { DotnetRuntimeProvider.GCCreateSegmentEvent.Descriptor, DotnetRuntimeProvider.GCCreateSegmentEvent.Name },
                        { DotnetRuntimeProvider.GCFreeSegmentEvent.Descriptor, DotnetRuntimeProvider.GCFreeSegmentEvent.Name },
                        { DotnetRuntimeProvider.GCRestartEEStartEvent.Descriptor, DotnetRuntimeProvider.GCRestartEEStartEvent.Name },
                        { DotnetRuntimeProvider.GCSuspendEEStopEvent.Descriptor, DotnetRuntimeProvider.GCSuspendEEStopEvent.Name },
                        { DotnetRuntimeProvider.GCSuspendEEStartEvent.Descriptor, DotnetRuntimeProvider.GCSuspendEEStartEvent.Name },
                        { DotnetRuntimeProvider.GCCreateConcurrentThreadEvent.Descriptor, DotnetRuntimeProvider.GCCreateConcurrentThreadEvent.Name },
                        { DotnetRuntimeProvider.GCTerminateConcurrentThreadEvent.Descriptor, DotnetRuntimeProvider.GCTerminateConcurrentThreadEvent.Name },
                        { DotnetRuntimeProvider.GCFinalizersStopEvent.Descriptor, DotnetRuntimeProvider.GCFinalizersStopEvent.Name },
                        { DotnetRuntimeProvider.GCFinalizersStartEvent.Descriptor, DotnetRuntimeProvider.GCFinalizersStartEvent.Name },
                        { DotnetRuntimeProvider.IOThreadCreationStartEvent.Descriptor, DotnetRuntimeProvider.IOThreadCreationStartEvent.Name },
                        { DotnetRuntimeProvider.IOThreadCreationStopEvent.Descriptor, DotnetRuntimeProvider.IOThreadCreationStopEvent.Name },
                        { DotnetRuntimeProvider.IOThreadRetirementStartEvent.Descriptor, DotnetRuntimeProvider.IOThreadRetirementStartEvent.Name },
                        { DotnetRuntimeProvider.IOThreadRetirementStopEvent.Descriptor, DotnetRuntimeProvider.IOThreadRetirementStopEvent.Name },
                        { DotnetRuntimeProvider.ExceptionStartEvent.Descriptor, DotnetRuntimeProvider.ExceptionStartEvent.Name },
                        { DotnetRuntimeProvider.ContentionStartEvent.Descriptor, DotnetRuntimeProvider.ContentionStartEvent.Name },
                        { DotnetRuntimeProvider.MethodJittingStartedEvent.Descriptor, DotnetRuntimeProvider.MethodJittingStartedEvent.Name },
                        { DotnetRuntimeProvider.LoaderDomainModuleLoadEvent.Descriptor, DotnetRuntimeProvider.LoaderDomainModuleLoadEvent.Name },
                        { DotnetRuntimeProvider.LoaderAssemblyLoadEvent.Descriptor, DotnetRuntimeProvider.LoaderAssemblyLoadEvent.Name },
                        { DotnetRuntimeProvider.LoaderAssemblyUnloadEvent.Descriptor, DotnetRuntimeProvider.LoaderAssemblyUnloadEvent.Name },
                        { DotnetRuntimeProvider.LoaderAppDomainLoadEvent.Descriptor, DotnetRuntimeProvider.LoaderAppDomainLoadEvent.Name },
                        { DotnetRuntimeProvider.LoaderAppDomainUnloadEvent.Descriptor, DotnetRuntimeProvider.LoaderAppDomainUnloadEvent.Name },
                        { DotnetRuntimeProvider.StrongNameVerificationStartEvent.Descriptor, DotnetRuntimeProvider.StrongNameVerificationStartEvent.Name },
                        { DotnetRuntimeProvider.StrongNameVerificationStopEvent.Descriptor, DotnetRuntimeProvider.StrongNameVerificationStopEvent.Name },
                        { DotnetRuntimeProvider.AuthenticodeVerificationStartEvent.Descriptor, DotnetRuntimeProvider.AuthenticodeVerificationStartEvent.Name },
                        { DotnetRuntimeProvider.AuthenticodeVerificationStopEvent.Descriptor, DotnetRuntimeProvider.AuthenticodeVerificationStopEvent.Name },
                        { DotnetRuntimeProvider.GCStartEvent.Descriptor, DotnetRuntimeProvider.GCStartEvent.Name },
                        { DotnetRuntimeProvider.MethodLoadEvent.Descriptor, DotnetRuntimeProvider.MethodLoadEvent.Name },
                        { DotnetRuntimeProvider.MethodUnloadEvent.Descriptor, DotnetRuntimeProvider.MethodUnloadEvent.Name },
                        { DotnetRuntimeProvider.MethodLoadVerboseEvent.Descriptor, DotnetRuntimeProvider.MethodLoadVerboseEvent.Name },
                        { DotnetRuntimeProvider.MethodUnloadVerboseEvent.Descriptor, DotnetRuntimeProvider.MethodUnloadVerboseEvent.Name },
                        { DotnetRuntimeProvider.LoaderModuleLoadEvent.Descriptor, DotnetRuntimeProvider.LoaderModuleLoadEvent.Name },
                        { DotnetRuntimeProvider.LoaderModuleUnloadEvent.Descriptor, DotnetRuntimeProvider.LoaderModuleUnloadEvent.Name },
                        { DotnetRuntimeProvider.GCJoinEvent.Descriptor, DotnetRuntimeProvider.GCJoinEvent.Name },
                        { DotnetRuntimeProvider.GCGlobalHeapHistoryEvent.Descriptor, DotnetRuntimeProvider.GCGlobalHeapHistoryEvent.Name },
                        { DotnetRuntimeProvider.GCAllocationTickEvent.Descriptor, DotnetRuntimeProvider.GCAllocationTickEvent.Name },
                        { DotnetRuntimeProvider.GCPerHeapHistoryEvent.Descriptor, DotnetRuntimeProvider.GCPerHeapHistoryEvent.Name },
                    }
                )
            },

            { 
                StreamJsonRpcProvider.Id,
                (
                    StreamJsonRpcProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { StreamJsonRpcProvider.EventSourceMessageEvent.Descriptor, StreamJsonRpcProvider.EventSourceMessageEvent.Name },
                        { StreamJsonRpcProvider.SendingNotificationEvent.Descriptor, StreamJsonRpcProvider.SendingNotificationEvent.Name },
                        { StreamJsonRpcProvider.ReceivedResultEvent.Descriptor, StreamJsonRpcProvider.ReceivedResultEvent.Name },
                        { StreamJsonRpcProvider.ReceivedErrorEvent.Descriptor, StreamJsonRpcProvider.ReceivedErrorEvent.Name },
                        { StreamJsonRpcProvider.ReceivedNoResponseEvent.Descriptor, StreamJsonRpcProvider.ReceivedNoResponseEvent.Name },
                        { StreamJsonRpcProvider.SendingCancellationRequestEvent.Descriptor, StreamJsonRpcProvider.SendingCancellationRequestEvent.Name },
                        { StreamJsonRpcProvider.ReceivedNotificationEvent.Descriptor, StreamJsonRpcProvider.ReceivedNotificationEvent.Name },
                        { StreamJsonRpcProvider.SendingResultEvent.Descriptor, StreamJsonRpcProvider.SendingResultEvent.Name },
                        { StreamJsonRpcProvider.SendingErrorEvent.Descriptor, StreamJsonRpcProvider.SendingErrorEvent.Name },
                        { StreamJsonRpcProvider.ReceivedCancellationRequestEvent.Descriptor, StreamJsonRpcProvider.ReceivedCancellationRequestEvent.Name },
                        { StreamJsonRpcProvider.TransmissionQueuedEvent.Descriptor, StreamJsonRpcProvider.TransmissionQueuedEvent.Name },
                        { StreamJsonRpcProvider.TransmissionCompletedEvent.Descriptor, StreamJsonRpcProvider.TransmissionCompletedEvent.Name },
                        { StreamJsonRpcProvider.HandlerTransmittedEvent.Descriptor, StreamJsonRpcProvider.HandlerTransmittedEvent.Name },
                        { StreamJsonRpcProvider.HandlerReceivedEvent.Descriptor, StreamJsonRpcProvider.HandlerReceivedEvent.Name },
                        { StreamJsonRpcProvider.SendingRequestEvent.Descriptor, StreamJsonRpcProvider.SendingRequestEvent.Name },
                        { StreamJsonRpcProvider.ReceivedRequestEvent.Descriptor, StreamJsonRpcProvider.ReceivedRequestEvent.Name },
                    }
                )
            },

            { 
                VisualStudioCpsCoreProvider.Id,
                (
                    VisualStudioCpsCoreProvider.Name, new Dictionary<EtwEventDescriptor, string>
                    {
                        { VisualStudioCpsCoreProvider.EventSourceMessageEvent.Descriptor, VisualStudioCpsCoreProvider.EventSourceMessageEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildStopEvent.Name },
                        { VisualStudioCpsCoreProvider.CreateItemSchemaStartEvent.Descriptor, VisualStudioCpsCoreProvider.CreateItemSchemaStartEvent.Name },
                        { VisualStudioCpsCoreProvider.CreateItemSchemaStopEvent.Descriptor, VisualStudioCpsCoreProvider.CreateItemSchemaStopEvent.Name },
                        { VisualStudioCpsCoreProvider.PublishingProjectCapabilitiesEvent.Descriptor, VisualStudioCpsCoreProvider.PublishingProjectCapabilitiesEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadDynamicLoadComponentsStartEvent.Descriptor, VisualStudioCpsCoreProvider.LoadDynamicLoadComponentsStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ConfiguredProjectVersionChangedEvent.Descriptor, VisualStudioCpsCoreProvider.ConfiguredProjectVersionChangedEvent.Name },
                        { VisualStudioCpsCoreProvider.ReportPrioritySchedulerGapEvent.Descriptor, VisualStudioCpsCoreProvider.ReportPrioritySchedulerGapEvent.Name },
                        { VisualStudioCpsCoreProvider.ReportProjectDataSourceVersionChangedEvent.Descriptor, VisualStudioCpsCoreProvider.ReportProjectDataSourceVersionChangedEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectEvaluationRuleSnapshotStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectEvaluationRuleSnapshotStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectEvaluationRuleSnapshotStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectEvaluationRuleSnapshotStopEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadSchemaFileStopEvent.Descriptor, VisualStudioCpsCoreProvider.LoadSchemaFileStopEvent.Name },
                        { VisualStudioCpsCoreProvider.PhysicalTreeLoadingStopEvent.Descriptor, VisualStudioCpsCoreProvider.PhysicalTreeLoadingStopEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadDynamicLoadComponentsStopEvent.Descriptor, VisualStudioCpsCoreProvider.LoadDynamicLoadComponentsStopEvent.Name },
                        { VisualStudioCpsCoreProvider.BatchBuildStartEvent.Descriptor, VisualStudioCpsCoreProvider.BatchBuildStartEvent.Name },
                        { VisualStudioCpsCoreProvider.BatchBuildStopEvent.Descriptor, VisualStudioCpsCoreProvider.BatchBuildStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildSnapshotStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildSnapshotStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildSnapshotStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildSnapshotStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectSnapshotStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectSnapshotStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectSnapshotStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectSnapshotStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildRuleSnapshotStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildRuleSnapshotStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectBuildRuleSnapshotStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectBuildRuleSnapshotStopEvent.Name },
                        { VisualStudioCpsCoreProvider.SubscribeRuleStartEvent.Descriptor, VisualStudioCpsCoreProvider.SubscribeRuleStartEvent.Name },
                        { VisualStudioCpsCoreProvider.SubscribeRuleStopEvent.Descriptor, VisualStudioCpsCoreProvider.SubscribeRuleStopEvent.Name },
                        { VisualStudioCpsCoreProvider.UpdateProjectRuleSnapshotStartEvent.Descriptor, VisualStudioCpsCoreProvider.UpdateProjectRuleSnapshotStartEvent.Name },
                        { VisualStudioCpsCoreProvider.UpdateProjectRuleSnapshotStopEvent.Descriptor, VisualStudioCpsCoreProvider.UpdateProjectRuleSnapshotStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectConfigurationActivatedEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectConfigurationActivatedEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectConfigurationDeactivatedEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectConfigurationDeactivatedEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectTreeProviderInitializationStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectTreeProviderInitializationStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectTreeProviderInitializationStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectTreeProviderInitializationStopEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadSchemaFileStartEvent.Descriptor, VisualStudioCpsCoreProvider.LoadSchemaFileStartEvent.Name },
                        { VisualStudioCpsCoreProvider.CreatePropertyCatalogsStartEvent.Descriptor, VisualStudioCpsCoreProvider.CreatePropertyCatalogsStartEvent.Name },
                        { VisualStudioCpsCoreProvider.CreatePropertyCatalogsStopEvent.Descriptor, VisualStudioCpsCoreProvider.CreatePropertyCatalogsStopEvent.Name },
                        { VisualStudioCpsCoreProvider.HintSubmissionStartEvent.Descriptor, VisualStudioCpsCoreProvider.HintSubmissionStartEvent.Name },
                        { VisualStudioCpsCoreProvider.HintSubmissionStopEvent.Descriptor, VisualStudioCpsCoreProvider.HintSubmissionStopEvent.Name },
                        { VisualStudioCpsCoreProvider.HintProcessStartEvent.Descriptor, VisualStudioCpsCoreProvider.HintProcessStartEvent.Name },
                        { VisualStudioCpsCoreProvider.HintProcessStopEvent.Descriptor, VisualStudioCpsCoreProvider.HintProcessStopEvent.Name },
                        { VisualStudioCpsCoreProvider.AddSourceItemsStartEvent.Descriptor, VisualStudioCpsCoreProvider.AddSourceItemsStartEvent.Name },
                        { VisualStudioCpsCoreProvider.AddSourceItemsStopEvent.Descriptor, VisualStudioCpsCoreProvider.AddSourceItemsStopEvent.Name },
                        { VisualStudioCpsCoreProvider.RemoveSourceItemsStartEvent.Descriptor, VisualStudioCpsCoreProvider.RemoveSourceItemsStartEvent.Name },
                        { VisualStudioCpsCoreProvider.RemoveSourceItemsStopEvent.Descriptor, VisualStudioCpsCoreProvider.RemoveSourceItemsStopEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadConfiguredProjectStartEvent.Descriptor, VisualStudioCpsCoreProvider.LoadConfiguredProjectStartEvent.Name },
                        { VisualStudioCpsCoreProvider.LoadConfiguredProjectStopEvent.Descriptor, VisualStudioCpsCoreProvider.LoadConfiguredProjectStopEvent.Name },
                        { VisualStudioCpsCoreProvider.PhysicalTreeLoadingStartEvent.Descriptor, VisualStudioCpsCoreProvider.PhysicalTreeLoadingStartEvent.Name },
                        { VisualStudioCpsCoreProvider.DirectoryTreeLoadingStartEvent.Descriptor, VisualStudioCpsCoreProvider.DirectoryTreeLoadingStartEvent.Name },
                        { VisualStudioCpsCoreProvider.DirectoryTreeLoadingStopEvent.Descriptor, VisualStudioCpsCoreProvider.DirectoryTreeLoadingStopEvent.Name },
                        { VisualStudioCpsCoreProvider.WaitAutoLoadMethodsToFinishStartEvent.Descriptor, VisualStudioCpsCoreProvider.WaitAutoLoadMethodsToFinishStartEvent.Name },
                        { VisualStudioCpsCoreProvider.WaitAutoLoadMethodsToFinishStopEvent.Descriptor, VisualStudioCpsCoreProvider.WaitAutoLoadMethodsToFinishStopEvent.Name },
                        { VisualStudioCpsCoreProvider.SetActiveTreeProviderStartEvent.Descriptor, VisualStudioCpsCoreProvider.SetActiveTreeProviderStartEvent.Name },
                        { VisualStudioCpsCoreProvider.SetActiveTreeProviderStopEvent.Descriptor, VisualStudioCpsCoreProvider.SetActiveTreeProviderStopEvent.Name },
                        { VisualStudioCpsCoreProvider.InitializeActiveTreeProviderStartEvent.Descriptor, VisualStudioCpsCoreProvider.InitializeActiveTreeProviderStartEvent.Name },
                        { VisualStudioCpsCoreProvider.InitializeActiveTreeProviderStopEvent.Descriptor, VisualStudioCpsCoreProvider.InitializeActiveTreeProviderStopEvent.Name },
                        { VisualStudioCpsCoreProvider.CapabilitiesTriggersProjectReloadEvent.Descriptor, VisualStudioCpsCoreProvider.CapabilitiesTriggersProjectReloadEvent.Name },
                        { VisualStudioCpsCoreProvider.UnloadDynamicLoadComponentsStartEvent.Descriptor, VisualStudioCpsCoreProvider.UnloadDynamicLoadComponentsStartEvent.Name },
                        { VisualStudioCpsCoreProvider.UnloadDynamicLoadComponentsStopEvent.Descriptor, VisualStudioCpsCoreProvider.UnloadDynamicLoadComponentsStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectGlobbingWatchingServiceInitializedEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectGlobbingWatchingServiceInitializedEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingConsistentCheckStartEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingConsistentCheckStartEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingConsistentCheckStopEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingConsistentCheckStopEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationStartEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationStartEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationStopEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectDirectoryTreeDisposedEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectDirectoryTreeDisposedEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectDirectoryTreeAddSubscriptionEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectDirectoryTreeAddSubscriptionEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectDirectoryTreeReleaseSubscriptionEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectDirectoryTreeReleaseSubscriptionEvent.Name },
                        { VisualStudioCpsCoreProvider.GetEvaluatedPropertyValueStartEvent.Descriptor, VisualStudioCpsCoreProvider.GetEvaluatedPropertyValueStartEvent.Name },
                        { VisualStudioCpsCoreProvider.GetEvaluatedPropertyValueStopEvent.Descriptor, VisualStudioCpsCoreProvider.GetEvaluatedPropertyValueStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectEvaluationStartEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectEvaluationStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectEvaluationStopEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectEvaluationStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ProjectMarkDirtiedEvent.Descriptor, VisualStudioCpsCoreProvider.ProjectMarkDirtiedEvent.Name },
                        { VisualStudioCpsCoreProvider.DesignTimeBuildStartEvent.Descriptor, VisualStudioCpsCoreProvider.DesignTimeBuildStartEvent.Name },
                        { VisualStudioCpsCoreProvider.DesignTimeBuildStopEvent.Descriptor, VisualStudioCpsCoreProvider.DesignTimeBuildStopEvent.Name },
                        { VisualStudioCpsCoreProvider.DesignTimeBuildFallbackToLegacyEvent.Descriptor, VisualStudioCpsCoreProvider.DesignTimeBuildFallbackToLegacyEvent.Name },
                        { VisualStudioCpsCoreProvider.UpToDateCheckCalculateHashStartEvent.Descriptor, VisualStudioCpsCoreProvider.UpToDateCheckCalculateHashStartEvent.Name },
                        { VisualStudioCpsCoreProvider.UpToDateCheckCalculateHashStopEvent.Descriptor, VisualStudioCpsCoreProvider.UpToDateCheckCalculateHashStopEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationUpgradeableLockRequestStartEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationUpgradeableLockRequestStartEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationUpgradeableLockRequestEndEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationUpgradeableLockRequestEndEvent.Name },
                        { VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationWriterLockRequestResultEvent.Descriptor, VisualStudioCpsCoreProvider.GlobbingWatchingTriggerReevaluationWriterLockRequestResultEvent.Name },
                        { VisualStudioCpsCoreProvider.ReportOutputDataSourceStartEvent.Descriptor, VisualStudioCpsCoreProvider.ReportOutputDataSourceStartEvent.Name },
                        { VisualStudioCpsCoreProvider.ReportOutputDataSourceStopEvent.Descriptor, VisualStudioCpsCoreProvider.ReportOutputDataSourceStopEvent.Name },
                        { VisualStudioCpsCoreProvider.ReportCoreDirectoryTreeHintFileChangedEvent.Descriptor, VisualStudioCpsCoreProvider.ReportCoreDirectoryTreeHintFileChangedEvent.Name },
                    }
                )
            },
        };
    }
}